baseURL = "/"
languageCode = "en-us"
title = "kate's lab notebook"
theme = "hugo-journal"
enableGitInfo = false

[Params]
	mainSections = ["post"]
	tagline = "unpolished technical \"content\" from @ktemkin"
	description = "unpolished technical \"content\" from @ktemkin"
	githubUsername = "ktemkin"
	twitterUsername = "ktemkin"

[Params.Author]
	name = "Kate Temkin"

[Params.work]
	jobTitle   = "CEO & Engineering Lead"
	company    = "Tactile Metrology"
	companyURL = "http://metrolo.gy"
